### ISSUE TITLE
TODOs / Ideas

### ISSUE THREAD

**Issue by l47y** [l47y/whatsappalytics#1]
## TODOs

- [x] When newline in one message they get splitted by my code --> fix it
- [x] Add inline code
- [x] Add example usage in readme
- [ ] App should show plot on the first time you click on upload
- [ ] Store wa object in app to not recalculate it everytime
- [ ] Include count media

**Comment by l47y** [comment]
## Ideas

- [x] Weekday activity (spider plot)
- [x] Overall chronological distribution
- [ ] Topic mining
- [ ] Sentiment plots
